helmfile/chartify

replace.go

Fixes https://github.com/roboll/helmfile/issues/1279
'helm template' writes to files manifest by manifest, appending to existing files as needed:
https://github.com/helm/helm/blob/v3.2.1/pkg/action/action.go#L192-L210
When helmfile feeds the list of files as resources to load to kustomize, this can lead to an error like "may not add resource with an already registered id" if duplicates aren't removed.
Minimal example (helm 3.1.3, kustomize 3.6.1, helmfile 0.118.1)
```yaml
repositories:
- name: stable
url: https://kubernetes-charts.storage.googleapis.com
releases:
- name: datadog
namespace: datadog-system
chart: stable/datadog
version: 2.3.5
values:
- clusterAgent:
datadog_cluster_yaml:
foo: bar
jsonPatches:
- target:
version: v1
kind: ConfigMap
name: datadog-cluster-agent-config
patch:
- …
```

Remove duplicates from the list of rendered files returned by ReplaceWithRendered

---

chartify.go
patch.go
replace.go

Fix is dedicated to enable usage of helmfile transformers on windows platform. 
All 3 fixes are related to path separators that behave different and were corrected to support linux and windows.

fix transformers on windows platform

---

.github/workflows/go.yml
patch.go
testdata/raw-manifests/input/configmap.yaml
testdata/raw-manifests/input/foo/configmap.2.yaml
testdata/raw-manifests/output/files/templates/configmap.yaml
testdata/raw-manifests/output/files/templates/foo/configmap.2.yaml

This PR fixes https://github.com/variantdev/chartify/issues/18

Fix #18: Better yaml doc separator

---

chartify.go
cmd/chartify/main.go
integration_test.go
replace.go

Some charts like gitlab/gitlab seem to have dependencies to its own sibling charts:
https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/requirements.yaml#L2-9
Apparently, chartify fails for such chart because how we handled adhoc dependencies.
The problem was that chartify was unnecessarily rerunning dependency downloads on the standard (non adhoc) chart dependencies declared in the chart.yaml and requirements.yaml, even though helm-fetch command that ran beforehand has already downloaded all of them.
This change fixes the issue by removing the already-downloaded chart dependencies out of Chart.yaml and requirements.yaml in case it is a remote chart. This way, it does not try to rerun dependency downloads hence it wont suffer from dependencies to sibling charts.
Ref …

Fix adhoc chart dependencies not working for some charts

---

.github/workflows/go.yml
replace.go
test_framework_test.go
testdata/integration/testcases/local_chart_with_adhoc_dependency/want

It turns out we only removed unnecessary dependencies from Chart.yaml and requirements.yaml, and not from Chart.lock and requirements.lock. These dangling lock files seem to result in the mentioned error.
Since this change, any remote or local chart that went through the chartify process will have all the lock files omitted, so that the error is gone. This is fine because all the original and adhoc dependencies are already included in the chartify output chart, due to that it is generated by `helm template`ing the original chart with various tweaks.
Ref https://github.com/roboll/helmfile/issues/2074#issuecomment-1068335836

Fix the lock-file-out-of-sync error with local chart + adhoc deps

---

chartify.go
integration_test.go
replace.go
tempdir_test.go
testdata/charts/vers/.helmignore
testdata/charts/vers/Chart.yaml
testdata/charts/vers/templates/NOTES.txt
testdata/charts/vers/templates/configmap.yaml
testdata/charts/vers/values.yaml
testdata/integration/testcases/kube_version_and_api_versions/want

Helm 3 recently re-introduced `kube-version` to `helm template`. This adds support for that.

Add support for --kube-version reintroduced in Helm 3

---

chartify.go
integration_test.go
testdata/chart_patch/deploy.db.strategic.yaml
testdata/integration/testcases/local_chart_with_dot_at_the_end/want
testdata/integration/testcases/local_chart_with_slash_at_the_end/want

Ref https://github.com/variantdev/chartify/pull/13

Fix kustomize patch failure due to missing helmx.1.rendered dir when the chart name ends with dot or slash

---

chartify.go
chartify_test.go
integration_test.go

It seems that [helmfile](https://github.com/helmfile/helmfile) doesn't support Helm chart hosted on OCI registry as adhoc dependencies.
helmfile.yaml:
```yaml
releases:
- name: nginx
namespace: default
chart: oci://asia-docker.pkg.dev/gcp-sample/helm-repo/nginx
version: 0.1.0
values:
- raw:
resources:
- apiVersion: v1
kind: ConfigMap
metadata:
name: extra-env
data:
FOO: bar
dependencies:
- chart: oci://asia-docker.pkg.dev/gcp-sample/helm-repo/raw
version: 0.1.0
```
I run into the problem while running `helmfile template` and got the following error:
```sh
❯ helmfile version
helmfile version v0.144.0
❯ helm repo list
NAME      	URL
bitnami   	https://charts.bitnami.com/bitnami
❯ helmfile --file test/oci/helmfile.yaml template
in test/oci/helmfile.yaml: [failed reading adhoc dependencies: …
```

feat: add OCI registry support for adhoc dependencies

---

kustomize.go

As I was trying to install an OperatorSDK project using Helmfile, I found that there was an error when setting the chart to a git repository in Helmfile. Helmfile clones the repository in a directory not relative to the current execution. Therefore, at the moment of charitfying the customization, Kustomize fails, because it can't find the source directory. As I traced the error, I found that the issue is that when generating the relative path, `KustomizeBuild` prepends the current working directory to the absolute path, which makes it fail.
I tested with the helmfile from https://github.com/helmfile/helmfile/blob/main/test/advanced/helmfile.yaml#L6-L9, replaced `kustomchart`'s chart with the repository reference:
```yaml
...
releases:
- name: kustomapp
chart: …
```

Fix kustomize bases relative path

---

chartify.go
integration_test.go
kustomize.go
patch.go
testdata/integration/testcases/kube_manifest_transformer_alpha_plugin/want
testdata/kube_manifest_transformer_alpha_plugin/annotations.yaml

feat: impl patch with alpha plugin flag. More information is here: https://github.com/helmfile/helmfile/discussions/827
I found that the helmfile HelmState structure passed `chartifyOpts.EnableKustomizeAlphaPlugins=true` to `chartify`, but it did not take effect in `chartify`.
For transformer and alpha plugin, I have added a integration test using the `AnnotationsTransformer` kustomize plugin
+ integration_test.go

feat: impl patch with alpha plugin flag.

---

runner.go

- Added `KustomizeBin` option to set a custom kustomize binary.
- Removed `KustomizeBinary` string value on `New` function because in Go strings are empty by default.

feat: add an option to set a custom kustomize binary

---

.gitignore
chartify.go
chartify_test.go
kustomize.go
testdata/integration/testcases/kustomize_with_helm_charts/want
testdata/kustomize_with_helm_charts/kustomization.yaml

This adds support --helm-binary for helmChart in kustomization.yaml by:
- Changing use helmBin() for kustomize build
Resolves https://github.com/helmfile/helmfile/issues/1121

feat: use helmBin() for kustomize build for helmChart in kustomization.yaml

---

patch.go

`patchesJson6902` directive has been deprecated on kustomize. 
`patches` is the replacement. 
The difference is explained [here](https://github.com/kubernetes-sigs/kustomize/issues/2705#issuecomment-659012281)
No Breaking change AFAIK

chore: use patches instead of deprecated patchesJson6902

---

.github/workflows/lint.yaml

https://github.com/golangci/golangci-lint/releases/tag/v1.60.1

chore: update golang-ci lint version

---

chartify.go
replace.go
tempdir_test.go

Adding `TemplateArgs` to allow passing any args to the helm template function.
I use this to pass `--dry-run=server` for helmfile apply (which is using helm template underneath) . This enables me to use the `lookup` functionality in my helm charts.
helmfile PR is already prepared and will follow.

feat: Adding template arguments

---

go.mod
go.sum

https://ogma.in/understanding-and-mitigating-cve-2024-45338-golang-denial-of-service-vulnerability

chore: resolving CVE-2024-45338

---

.github/workflows/go.yml

This pull request includes a small change to the `.github/workflows/go.yml` file. The change updates the Helm version from `v3.17.0` to `v3.17.1`.

build: update Helm version to v3.17.1

---

.github/workflows/lint.yaml
go.mod

This pull request includes updates to the Go version and the Golangci-lint version used in the project. The most important changes are:
* [`.github/workflows/lint.yaml`](diffhunk://#diff-4b122024a3a28ded65da76a2f1bface1f3a27328374438d1298d25585fe0603bL27-R27): Updated the Golangci-lint version from `v1.61.0` to `v1.64.5`.
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L3-R3): Updated the Go version from `1.23.0` to `1.24`.

build: update golang version to 1.24 and golangci-lint to v1.64.5

---

.github/workflows/go.yml

This pull request includes a minor version update for the Helm tool in the GitHub Actions workflow configuration file. The change updates the Helm version from v3.17.1 to v3.17.2 to ensure the workflow uses the latest version.
* [`.github/workflows/go.yml`](diffhunk://#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fL25-R25): Updated Helm version from v3.17.1 to v3.17.2.

build: update Helm version to v3.17.2

---

.github/workflows/go.yml

This pull request includes changes to the `.github/workflows/go.yml` file to streamline the installation process for Helm and Kustomize in the CI workflow. The most important changes involve replacing manual installation steps with GitHub Actions for better maintainability and simplicity.
Improvements to the CI workflow:
* [`.github/workflows/go.yml`](diffhunk://#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fL21-R32): Replaced manual Helm installation with `azure/setup-helm@v4.3.0` GitHub Action.
* [`.github/workflows/go.yml`](diffhunk://#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fL21-R32): Replaced manual Kustomize installation with `syntaqx/setup-kustomize@v1` GitHub Action.

refactor(workflows): simplify Helm and Kustomize installation

---

.github/workflows/go.yml

This pull request includes a small change to the `.github/workflows/go.yml` file. The change updates the Helm version used in the workflow from `v3.17.2` to `v3.17.3`.

build: update Helm to version v3.17.3

---

.github/workflows/go.yml

This pull request updates the Helm version used in the GitHub Actions workflow for Go projects.
* [`.github/workflows/go.yml`](diffhunk://#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fL24-R24): Updated the Helm version from `v3.17.3` to `v3.18.0` in the workflow configuration.

build: update Helm to version v3.18.0

---

testdata/integration/testcases/kube_version_and_api_versions/want

This pull request updates the `want` test data for Kubernetes API versions in the `testdata/integration/testcases/kube_version_and_api_versions` directory. The changes involve replacing and reordering several API versions to align with updated specifications.
Updates to Kubernetes API versions:
* Replaced `resource.k8s.io/v1beta1` with `resource.k8s.io/v1beta2` and reintroduced `resource.k8s.io/v1beta1` in the correct order.
* Reordered and reintroduced several API versions (`scheduling.k8s.io`, `storage.k8s.io`, `storagemigration.k8s.io`, `apiextensions.k8s.io`, and custom APIs like `foo`, `bar`, and `baz`) to ensure proper alignment with the updated test data structure.

fix(testdata): update kube and api versions in test case

---

util.go
util_test.go

This pull request improves the robustness and usability of the `FindSemVerInfo` utility function by handling empty and non-prefixed version strings, and updates the related tests to reflect the new behavior.
Enhancements to version string handling:
* Updated `FindSemVerInfo` in `util.go` to return an error if the input version string is empty and to automatically add a `v` prefix if it's missing before extracting the semantic version.
Test updates:
* Modified the test case in `util_test.go` to expect a valid semver result when the version string does not start with `v`, reflecting the new logic in `FindSemVerInfo`.

fix: validate and preprocess version in FindSemVerInfo
